# Header
menu:
	Home: /
	Details: /details
	Accessibility: /access
	Contact: /contact

# URL of the Home page image
title-background: /images/title.jpg

# Default post title
default_post_title: Untitled

# Google Analytics
google_analytics:

# Favicon
favicon:
